projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: 262v4bsuvbf6lairtyrju33su4
        frontend: javascript
        framework: react-native
        maxDepth: 4
extensions:
  amplify:
    version: 3
